export const ADD_BOARD_ITEM = 'ADD_BOARD_ITEM';
export const UPDATE_BOARD_ITEM = 'UPDATE_BOARD_ITEM';
export const DELETE_BOARD_ITEM = 'DELETE_BOARD_ITEM';

export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';

export const ADD_CARD_ITEM = 'ADD_CARD_ITEM';
export const UPDATE_CARD_ITEM = 'UPDATE_CARD_ITEM';
export const DELETE_CARD_ITEM = 'DELETE_CARD_ITEM';

export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';