export const ADD_CARD_MODAL = 'ADD_CARD_MODAL';
export const EDIT_CARD_MODAL = 'EDIT_CARD_MODAL';
export const ADD_LIST_MODAL = 'ADD_LIST_MODAL';
export const EDIT_LIST_MODAL = 'EDIT_LIST_MODAL';
export const EDIT_BOARD_MODAL = 'EDIT_BOARD_MODAL';
export const ADD_BOARD_MODAL = 'ADD_BOARD_MODAL';